from flask import Flask, render_template, request, redirect
import json
import sqlite3
from sqlite3 import Error
import csv
from datetime import datetime
import pytz
from copy import deepcopy

# Database path
DB = "/home/JRdrama/mysite/drama.db"

app = Flask(__name__)

def connect_db(db_file):
    """
    Connects tot the database
    ARGS:
        db_file: the pah to the database file
    RETURNS:
        connection, which is the connection to the database. none if no connection is established
    """
    try:
        connection = sqlite3.connect(db_file)
        cursor = connection.cursor()
        print("CONN")
        return cursor, connection
    except Error as e:
        print(e)
        return none

def get_attendance_data(cur, con):

    # Move the cursor to select the data.
    #cur.execute("DELETE FROM attendance;")
    #con.commit()
    cur.execute("SELECT DISTINCT date FROM attendance;")
    # Get the all of the different dates that attendance hasbeen taken on.
    dates = cur.fetchall()
    record = {}
    for day in dates:
        # For every day, now get the attendance for that day. the use of f string here is fine, as it processes data from the database which has been autogenerated. (The date)
        cur.execute(f"SELECT date, present, personID FROM attendance WHERE date = {day[0]} ORDER BY personID ;")
        record_day = cur.fetchall()

        # Copies the datastructute to allow for changes during itteration.
        rd_copy = deepcopy(record_day)
        for i, person in enumerate(record_day):
            cur.execute(f"SELECT fname, lname, role FROM people WHERE id = {person[2]}")
            person_data = cur.fetchall()
            # Append the person data to the attendance data by creating a new tuple
            rd_copy[i] = (person[0], person[1], person_data)
        # Adds all of the person and attendance data just collected to the 'record' dict to be returned in html
        record[day[0]] = rd_copy
    # close the connection when done, prevents issues like memory leaks
    return record

# Retrive data from jsons and csvs. all of this is temp, and should be replaced with DB sql
with open("/home/JRdrama/mysite/static/people.json", encoding='utf8') as f:
    people = json.load(f)['people']
with open("/home/JRdrama/mysite/static/lines.json", encoding='utf8') as f:
    lines = json.load(f)
with open("/home/JRdrama/mysite/static/people.csv", 'r', newline='', encoding='utf8') as csvfile:
        reader = csv.reader(csvfile)
        people_csv = list(map(tuple, reader))



@app.route('/')
def roll():
    """Takes the roll
    """

    cur, con = connect_db(DB)

    cur.execute("SELECT fname, lname, role, id FROM people")
    # Get the data from where the cursor is
    people_list = cur.fetchall()
    print(people_list)
    # close the connection when done, prevents issues like memory leaks
    con.close()
    return render_template("roll.html", people=people_list)

@app.route('/roll')
def roll_updated():
    """Takes the roll
    """

    cur, con = connect_db(DB)
    record = get_attendance_data(cur, con)



    today = "2" + datetime.now(pytz.timezone("Pacific/Auckland")).strftime("%d%m%Y")

    if int(today) not in record:
        # Get the last attendance record
        record_append = [list(item) for item in list(record.values())[0]]
        l = len(record_append)
        for num in range(l):
            item = list(record_append[num])
            item[0] = today
            item[1] = 0
            record_append[num] = item
        print(record_append)
        record[today] = record_append
    cur.execute("SELECT fname, lname, role, id FROM people")
    # Get the data from where the cursor is
    people_list = cur.fetchall()
    print(people_list)
    # close the connection when done, prevents issues like memory leaks
    con.close()

    # jinja and json are STUPID and demand keys which are strings:
    new_record = {}
    for k,v in record.items():
        new_record[str(k)] = v
    return render_template("rollupdated.html", people=people_list, record=new_record)

@app.route('/data/<id>')
def data_name(id):
    """
    Presents the data of a particular person

    Args:
        id: the id of ther persons attendance to

    Returns:
        A html page with their data.
    """
    cur, con = connect_db(DB)

    # Move the cursor to select the data.
    cur.execute("SELECT * FROM people WHERE id = ?;", (id,))
    person_data = cur.fetchall()[0]
    cur.execute("SELECT * FROM attendance WHERE personID = ?;", (id,))
    attendance_data = cur.fetchall()
    con.close()
    line_counts = {}
    for scene, counts in lines.items():
        if person_data[3] in counts:
            # line data from json is indexed by character name
            line_counts[scene] = counts[person_data[3]]


    return render_template("data.html", data=[person_data, attendance_data, line_counts])



@app.route('/attendance')
def attendance():
    """Presents attendance
    """
    #print(people)
    cur, con = connect_db(DB)
    record = get_attendance_data(cur, con)
    # close the connection when done, prevents issues like memory leaks
    con.close()
    return render_template("attendance.html", record=record)


@app.route('/best', methods=["POST"])
def best():
    """Presents the results of who is present
    """
    if request.form.get("dummy") == "1":
        # For not overwriting data when demonstrating
        return redirect("/")
    else:
        today = "2" + datetime.now(pytz.timezone("Pacific/Auckland")).strftime("%d%m%Y")

        cur, con = connect_db(DB)


        cur.execute("SELECT id, fname, lname, role FROM people")
        current_attendance = cur.fetchall()
        # Restructures the returned data from a list to a dict with a key of th id.
        attendance_dict = {p[0]: list(p[1:]) for p in current_attendance}

        # Copy the data so we dont delete items from the dict we are itterating through while we itterate through it.
        ad = deepcopy(attendance_dict)

        # The whole loop is to add the people who were not there, as the data returned from the form does not include unmarked check boxes.
        for actor, data in attendance_dict.items():
            if str(actor) in dict(request.form):
                # If the actor was present.
                ad[actor].append(True)
            elif request.form.get("or") == "1":
                # If the user submited 'or' then
                del ad[actor]
            else:
                ad[actor].append(False)
        attendance_dict = ad
        insert_data = [(f"{today}_{id}", today, attendance_dict[id][3], id) for id in attendance_dict.keys()]

        # Insert or replace is used for both updating data with more recent attendance data and for adding new data for new days
        cur.executemany("INSERT OR REPLACE INTO attendance(itemID, date, present, personID) VALUES (?, ?, ?, ?)", insert_data)

        con.commit()
        con.close()
        scene_scores = {}
        for scene, chars in lines.items():
            temp_score = 0
            for id, char_dat in attendance_dict.items():
                if char_dat[3] and char_dat[2] in chars:
                    # Add the number of lines
                    temp_score += chars[char_dat[2]]
            scene_scores[scene] = temp_score/chars["total"]
    #scene_scores
        return render_template("best.html", scenes=dict(sorted(scene_scores.items(), key=lambda item: item[1], reverse=True)))


@app.route('/better', methods=["POST"])
def better():
    """Presents the results of who is present
    """
    print(request.form)
    today = int(request.form.get("date"))
    print(today)


    cur, con = connect_db(DB)


    cur.execute("SELECT id, fname, lname, role FROM people")
    current_attendance = cur.fetchall()
    # Restructures the returned data from a list to a dict with a key of th id.
    attendance_dict = {p[0]: list(p[1:]) for p in current_attendance}

    # Copy the data so we dont delete items from the dict we are itterating through while we itterate through it.
    ad = deepcopy(attendance_dict)

    # The whole loop is to add the people who were not there, as the data returned from the form does not include unmarked check boxes.
    for actor, data in attendance_dict.items():
        if str(actor) in dict(request.form):
            # If the actor was present.
            ad[actor].append(True)
        else:
            ad[actor].append(False)
    attendance_dict = ad
    insert_data = [(f"{today}_{id}", today, attendance_dict[id][3], id) for id in attendance_dict.keys()]

    # Insert or replace is used for both updating data with more recent attendance data and for adding new data for new days
    cur.executemany("INSERT OR REPLACE INTO attendance(itemID, date, present, personID) VALUES (?, ?, ?, ?)", insert_data)

    con.commit()
    con.close()
    scene_scores = {}
    for scene, chars in lines.items():
        temp_score = 0
        for id, char_dat in attendance_dict.items():
            if char_dat[3] and char_dat[2] in chars:
                # Add the number of lines
                temp_score += chars[char_dat[2]]
        scene_scores[scene] = temp_score/chars["total"]

    return render_template("best.html", scenes=dict(sorted(scene_scores.items(), key=lambda item: item[1], reverse=True)))

@app.route('/admin')
def admin():
    return render_template('admin.html')
